name: MiningContest
version: '${project.version}'
main: net.danh.miningcontest.MiningContest
api-version: '1.13'
authors: [ VoChiDanh ]
softdepend:
  - WorldGuard
  - PlaceholderAPI
  - ItemsAdder
commands:
  MiningContest:
    description: MiningContest Command
    aliases:
      - mc
